services:
  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    image: payflow-payment-service:dev
    container_name: payflow-payment-service
    environment:
      DATABASE_URL: ${DATABASE_URL}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      APP_HOST: ${APP_HOST}
      APP_PORT: ${APP_PORT}
    ports:
      - "${PAYMENT_SERVICE_PORT}:${APP_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
  postgres:
    image: postgres:17-alpine
    container_name: payflow-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  redis:
    image: redis:8-alpine
    container_name: payflow-redis
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  kafka:
    image: apache/kafka:4.3.1
    hostname: kafka
    container_name: payflow-kafka
    ports:
      - "${KAFKA_HOST_PORT}:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >-
        CONTROLLER:PLAINTEXT,
        INTERNAL:PLAINTEXT,
        EXTERNAL:PLAINTEXT

      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"

      KAFKA_LISTENERS: >-
        CONTROLLER://:29093,
        INTERNAL://:9092,
        EXTERNAL://:29092

      KAFKA_ADVERTISED_LISTENERS: >-
        INTERNAL://kafka:9092,
        EXTERNAL://localhost:${KAFKA_HOST_PORT}

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      CLUSTER_ID: ${KAFKA_CLUSTER_ID}

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR: 1

      KAFKA_LOG_DIRS: "/var/lib/kafka/data"

    volumes:
      - kafka_data:/var/lib/kafka/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list >/dev/null 2>&1",
        ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s

volumes:
  postgres_data:
  kafka_data:
