"""add unpublished outbox index

Revision ID: 1bf6b0ac71da
Revises: 2f6adb130a13
Create Date: 2026-08-01 14:24:09.591281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bf6b0ac71da'
down_revision: Union[str, Sequence[str], None] = '2f6adb130a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_outbox_events_unpublished_created_at_id', 'outbox_events', ['created_at', 'id'], unique=False, postgresql_where=sa.text('published IS FALSE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outbox_events_unpublished_created_at_id', table_name='outbox_events', postgresql_where=sa.text('published IS FALSE'))
    # ### end Alembic commands ###
